services:

  db:
    image: postgres
    restart: always
    environment:
<<<<<<< HEAD
    - POSTGRES_USER="${POSTGRES_USER}"
    - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    - POSTGRES_DB="${POSTGRES_DB}"
    ports:
      - "5432:5432"
=======
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      ports:
      - 5432:5432
>>>>>>> 910c85ea2fed2867da42ca4aff2633ee455f8ec1
